version: '3'
services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
  postgres-db:
    image: 'postgres:12'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=node_gmp
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=node_gmp
    restart: always
    ports:
      - '5432:5432'
  