version: '3'
services:
  app:
    container_name: my_app
    image: 'my_app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TOKEN_KEY=someverysecterstring
      - NODE_ENV=development
      - SERVER_PORT=3000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - my_network
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - TOKEN_KEY=someverysecterstring
      - NODE_ENV=development
      - SERVER_PORT=3000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    restart: always
    volumes:
      - postgres:/data/db
      - postgres_config:/data/configdb
    networks:
      - my_network
    ports:
      - '5432:5432'
networks:
  my_network:
volumes:
  postgres:
  postgres_config:

